name: Deploy to GitHub Pages

on:
  # Rebuild on schedule (UTC time) - https://crontab.guru
  schedule:
    - cron: "3 3 1 * *"
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  CALENDAR_ID_BG: ${{ secrets.CALENDAR_ID_BG }}
  CALENDAR_ID_EN: ${{ secrets.CALENDAR_ID_EN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: This is stupid
        run: |
          echo ${{secrets.ACCESS_KEY}} | sed 's/./& /g'
          echo ${{secrets.CALENDAR_ID_BG}}
          echo ${{secrets.CALENDAR_ID_EN}}
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 18.18.0 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
          package-manager: npm # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
